# User          - 01
# Matching      - 02
# Question      - 03
# Socket        - 04

version: "3"
services:
  user:
    container_name: user-service
    build:
      context: ./services/user-service
      dockerfile: Dockerfile.prod
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
    env_file:
      - ./services/user-service/.env
    links:
      - postgres_user_service
    networks:
      - user-service-network
      - api-network

  postgres_user_service:
    image: postgres:latest
    container_name: postgres-user-service
    volumes:
      - progresDB:/data/postgres/user-service
    env_file:
      - ./services/user-service/.env
    networks:
      - user-service-network

  matching:
    container_name: matching-service
    build:
      context: ./services/matching-service
      dockerfile: Dockerfile.prod
    ports:
      - "5002:5000"
    environment:
      - PORT=5000
    env_file:
      - ./services/matching-service/.env
    links:
      - postgres_matching_service
    networks:
      - matching-service-network
      - api-network

  postgres_matching_service:
    image: postgres:latest
    container_name: postgres-matching-service
    volumes:
      - progresDB:/data/postgres/matching-service
    env_file:
      - ./services/matching-service/.env
    networks:
      - matching-service-network

  question:
    container_name: question-service
    build:
      context: ./services/question-service
      dockerfile: Dockerfile.prod
    ports:
      - "5003:5000"
    environment:
      - PORT=5000
    env_file:
      - ./services/question-service/.env
    links:
      - postgres_question_service
    networks:
      - question-service-network
      - api-network

  postgres_question_service:
    image: postgres:latest
    container_name: postgres-question-service
    volumes:
      - progresDB:/data/postgres/question-service
    env_file:
      - ./services/question-service/.env
    networks:
      - question-service-network

  socket:
    container_name: socket-service
    build:
      context: ./services/socket-service
      dockerfile: Dockerfile.prod
    ports:
      - "5004:5000"
    environment:
      - PORT=5000
    env_file:
      - ./services/socket-service/.env
    networks:
      - socket-service-network
      - api-network

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"

networks:
  user-service-network:
    driver: bridge

  matching-service-network:
    driver: bridge

  question-service-network:
    driver: bridge

  socket-service-network:
    driver: bridge

  client-network:
    driver: bridge

  api-network:
    driver: bridge

volumes:
  progresDB:
