FROM node:20-alpine

# Add package file
COPY package.json ./
COPY yarn.lock ./
COPY ./prisma ./prisma

# Install deps
RUN yarn install

# Run prisma generate
RUN npx prisma generate

# Copy source
COPY src ./src
COPY tsconfig.json ./tsconfig.json
COPY tsconfig.build.json ./tsconfig.build.json

# Build dist
RUN yarn build

EXPOSE 5000

CMD yarn run dev:migrate
